// Community-sorted CHM13/hs1 UCSC browser slide suite.
// Generated by _scripts/render_ucsc_browser_suite_by_community.py.

#set page(
  width: 13.33in,
  height: 7.5in,
  margin: (x: 0.18in, y: 0.14in),
)
#set text(font: "DejaVu Sans", size: 9pt, lang: "en")
#set par(justify: false, leading: 0.62em)

#let col-title = rgb("#1a3a6b")
#let col-muted = rgb("#555555")
#let col-link = rgb("#135f9f")
#let col-rule = rgb("#ccd6e0")
#let col-chip = rgb("#e7eef7")

#let browser-panel(community, label, region, details, members, img, url) = {
  box(width: 100%)[
    #grid(
      columns: (0.48in, 0.78in, 1fr, auto),
      column-gutter: 0.08in,
      align: (left, left, left, right),
      [#box(inset: (x: 0.05in, y: 0.012in), radius: 1.5pt, fill: col-chip)[#text(size: 8pt, weight: "bold", fill: col-title)[#community]]],
      [#text(size: 10pt, weight: "semibold", fill: col-title)[#label]],
      [#text(size: 7.1pt, fill: col-muted)[#details]],
      [#text(size: 7.3pt, fill: col-muted)[#region]],
    )
    #v(0.006in)
    #text(size: 5.25pt, fill: col-link)[#link(url)[#url]]
    #v(0.01in)
    #image(img, width: 100%)
  ]
}


#align(center + horizon)[
  #block(width: 11.4in)[
    #align(center)[#text(size: 25pt, weight: "bold", fill: col-title)[CHM13/hs1 PHR Browser Panels by Community]]
    #v(0.22in)
    #text(size: 13pt)[37 cached UCSC Genome Browser panels sorted by the HPRCv2 arm-level Leiden C1-C15 community assignments. Panels keep the same full-width image scale as the original browser suite; multiple panels are stacked only when they fit at that scale.]
    #v(0.16in)
    #text(size: 10.5pt, fill: col-muted)[Every panel includes a visible, clickable UCSC URL. Browser windows are terminal-anchored 1.5x zoom-outs around the CHM13 PHR interval.]
    #v(0.16in)
    #text(size: 10pt, fill: col-muted)[Rendered arms absent from the CHM13 BED remain absent here: C5 missing from chm13.phrs.bed: chr6p; C7 missing from chm13.phrs.bed: chr13p; C14 missing from chm13.phrs.bed: chrYq; C15 missing from chm13.phrs.bed: chrYp.]
    #v(0.16in)
    #text(size: 9.2pt, fill: col-muted)[Sources: `manifest.tsv`; `hprcv2.1Mb.subtelo.arm-leiden-k15.assignments.tsv`; `arm_order_community.tsv`. Layout audit: `manifest_by_community.tsv`.]
  ]
]

#pagebreak()

#browser-panel("C1", "chr10q", "chr10:134,488,135-134,758,134", "PHR 180 kbp; window 270 kbp; terminal gap 3.14 kbp; C arms 4q, 10q", "4q, 10q", "_assets/ucsc/panels/chr10q_chr10_134488135_134758134.png", "https://genome.ucsc.edu/cgi-bin/hgTracks?db=hub_3671779_hs1&hgsid=3966979908_lGks6rs34CqmdawD8iwY2YCYKVd3&position=chr10%3A134488135-134758134&pix=1800")

#v(0.07in)

#browser-panel("C1", "chr4q", "chr4:193,304,946-193,574,945", "PHR 180 kbp; window 270 kbp; terminal gap 2.21 kbp; C arms 4q, 10q", "4q, 10q", "_assets/ucsc/panels/chr4q_chr4_193304946_193574945.png", "https://genome.ucsc.edu/cgi-bin/hgTracks?db=hub_3671779_hs1&hgsid=3966979908_lGks6rs34CqmdawD8iwY2YCYKVd3&position=chr4%3A193304946-193574945&pix=1800")

#pagebreak()

#browser-panel("C2", "chr10p", "chr10:1-105,002", "PHR 70 kbp; window 105 kbp; terminal gap 2.49 kbp; C arms 10p, 18p", "10p, 18p", "_assets/ucsc/panels/chr10p_chr10_1_105002.png", "https://genome.ucsc.edu/cgi-bin/hgTracks?db=hub_3671779_hs1&hgsid=3966979908_lGks6rs34CqmdawD8iwY2YCYKVd3&position=chr10%3A1-105002&pix=1800")

#v(0.07in)

#browser-panel("C2", "chr18p", "chr18:1-397,502", "PHR 265 kbp; window 398 kbp; terminal gap 2.02 kbp; C arms 10p, 18p", "10p, 18p", "_assets/ucsc/panels/chr18p_chr18_1_397502.png", "https://genome.ucsc.edu/cgi-bin/hgTracks?db=hub_3671779_hs1&hgsid=3966979908_lGks6rs34CqmdawD8iwY2YCYKVd3&position=chr18%3A1-397502&pix=1800")

#pagebreak()

#browser-panel("C3", "chr11p", "chr11:1-352,502", "PHR 235 kbp; window 353 kbp; terminal gap 1.74 kbp; C arms 3q, 7p, 9q, 11p, 16q, 19p", "3q, 7p, 9q, 11p, 16q, 19p", "_assets/ucsc/panels/chr11p_chr11_1_352502.png", "https://genome.ucsc.edu/cgi-bin/hgTracks?db=hub_3671779_hs1&hgsid=3966979908_lGks6rs34CqmdawD8iwY2YCYKVd3&position=chr11%3A1-352502&pix=1800")

#pagebreak()

#browser-panel("C3", "chr19p", "chr19:1-315,002", "PHR 210 kbp; window 315 kbp; terminal gap 1.96 kbp; C arms 3q, 7p, 9q, 11p, 16q, 19p", "3q, 7p, 9q, 11p, 16q, 19p", "_assets/ucsc/panels/chr19p_chr19_1_315002.png", "https://genome.ucsc.edu/cgi-bin/hgTracks?db=hub_3671779_hs1&hgsid=3966979908_lGks6rs34CqmdawD8iwY2YCYKVd3&position=chr19%3A1-315002&pix=1800")

#pagebreak()

#browser-panel("C3", "chr3q", "chr3:200,723,449-201,105,948", "PHR 255 kbp; window 382 kbp; terminal gap 4.59 kbp; C arms 3q, 7p, 9q, 11p, 16q, 19p", "3q, 7p, 9q, 11p, 16q, 19p", "_assets/ucsc/panels/chr3q_chr3_200723449_201105948.png", "https://genome.ucsc.edu/cgi-bin/hgTracks?db=hub_3671779_hs1&hgsid=3966979908_lGks6rs34CqmdawD8iwY2YCYKVd3&position=chr3%3A200723449-201105948&pix=1800")

#v(0.07in)

#browser-panel("C3", "chr9q", "chr9:150,279,748-150,617,247", "PHR 225 kbp; window 338 kbp; terminal gap 2.22 kbp; C arms 3q, 7p, 9q, 11p, 16q, 19p", "3q, 7p, 9q, 11p, 16q, 19p", "_assets/ucsc/panels/chr9q_chr9_150279748_150617247.png", "https://genome.ucsc.edu/cgi-bin/hgTracks?db=hub_3671779_hs1&hgsid=3966979908_lGks6rs34CqmdawD8iwY2YCYKVd3&position=chr9%3A150279748-150617247&pix=1800")

#pagebreak()

#browser-panel("C3", "chr16q", "chr16:96,097,875-96,330,374", "PHR 155 kbp; window 232 kbp; terminal gap 2.56 kbp; C arms 3q, 7p, 9q, 11p, 16q, 19p", "3q, 7p, 9q, 11p, 16q, 19p", "_assets/ucsc/panels/chr16q_chr16_96097875_96330374.png", "https://genome.ucsc.edu/cgi-bin/hgTracks?db=hub_3671779_hs1&hgsid=3966979908_lGks6rs34CqmdawD8iwY2YCYKVd3&position=chr16%3A96097875-96330374&pix=1800")

#pagebreak()

#browser-panel("C3", "chr7p", "chr7:1-262,502", "PHR 175 kbp; window 263 kbp; terminal gap 3.38 kbp; C arms 3q, 7p, 9q, 11p, 16q, 19p", "3q, 7p, 9q, 11p, 16q, 19p", "_assets/ucsc/panels/chr7p_chr7_1_262502.png", "https://genome.ucsc.edu/cgi-bin/hgTracks?db=hub_3671779_hs1&hgsid=3966979908_lGks6rs34CqmdawD8iwY2YCYKVd3&position=chr7%3A1-262502&pix=1800")

#v(0.07in)

#browser-panel("C4", "chr12q", "chr12:133,287,049-133,324,548", "PHR 25 kbp; window 37.5 kbp; terminal gap 2.27 kbp; C arms 7q, 12q", "7q, 12q", "_assets/ucsc/panels/chr12q_chr12_133287049_133324548.png", "https://genome.ucsc.edu/cgi-bin/hgTracks?db=hub_3671779_hs1&hgsid=3966979908_lGks6rs34CqmdawD8iwY2YCYKVd3&position=chr12%3A133287049-133324548&pix=1800")

#v(0.07in)

#browser-panel("C4", "chr7q", "chr7:160,559,929-160,567,428", "PHR 5 kbp; window 7.50 kbp; terminal gap 1.83 kbp; C arms 7q, 12q", "7q, 12q", "_assets/ucsc/panels/chr7q_chr7_160559929_160567428.png", "https://genome.ucsc.edu/cgi-bin/hgTracks?db=hub_3671779_hs1&hgsid=3966979908_lGks6rs34CqmdawD8iwY2YCYKVd3&position=chr7%3A160559929-160567428&pix=1800")

#pagebreak()

#browser-panel("C5", "chr9p", "chr9:1-60,002", "PHR 40 kbp; window 60 kbp; terminal gap 3.49 kbp; C arms 6p, 9p, 12p, 20q", "6p, 9p, 12p, 20q", "_assets/ucsc/panels/chr9p_chr9_1_60002.png", "https://genome.ucsc.edu/cgi-bin/hgTracks?db=hub_3671779_hs1&hgsid=3966979908_lGks6rs34CqmdawD8iwY2YCYKVd3&position=chr9%3A1-60002&pix=1800")

#v(0.07in)

#browser-panel("C5", "chr12p", "chr12:1-105,002", "PHR 70 kbp; window 105 kbp; terminal gap 2.78 kbp; C arms 6p, 9p, 12p, 20q", "6p, 9p, 12p, 20q", "_assets/ucsc/panels/chr12p_chr12_1_105002.png", "https://genome.ucsc.edu/cgi-bin/hgTracks?db=hub_3671779_hs1&hgsid=3966979908_lGks6rs34CqmdawD8iwY2YCYKVd3&position=chr12%3A1-105002&pix=1800")

#pagebreak()

#browser-panel("C5", "chr20q", "chr20:66,052,756-66,210,255", "PHR 105 kbp; window 158 kbp; terminal gap 2.89 kbp; C arms 6p, 9p, 12p, 20q", "6p, 9p, 12p, 20q", "_assets/ucsc/panels/chr20q_chr20_66052756_66210255.png", "https://genome.ucsc.edu/cgi-bin/hgTracks?db=hub_3671779_hs1&hgsid=3966979908_lGks6rs34CqmdawD8iwY2YCYKVd3&position=chr20%3A66052756-66210255&pix=1800")

#v(0.07in)

#browser-panel("C6", "chr17q", "chr17:84,209,398-84,276,897", "PHR 45 kbp; window 67.5 kbp; terminal gap 2.79 kbp; C arms 1q, 13q, 17q, 19q, 21q, 22q", "1q, 13q, 17q, 19q, 21q, 22q", "_assets/ucsc/panels/chr17q_chr17_84209398_84276897.png", "https://genome.ucsc.edu/cgi-bin/hgTracks?db=hub_3671779_hs1&hgsid=3966979908_lGks6rs34CqmdawD8iwY2YCYKVd3&position=chr17%3A84209398-84276897&pix=1800")

#v(0.07in)

#browser-panel("C6", "chr13q", "chr13:113,551,687-113,566,686", "PHR 10 kbp; window 15 kbp; terminal gap 3.44 kbp; C arms 1q, 13q, 17q, 19q, 21q, 22q", "1q, 13q, 17q, 19q, 21q, 22q", "_assets/ucsc/panels/chr13q_chr13_113551687_113566686.png", "https://genome.ucsc.edu/cgi-bin/hgTracks?db=hub_3671779_hs1&hgsid=3966979908_lGks6rs34CqmdawD8iwY2YCYKVd3&position=chr13%3A113551687-113566686&pix=1800")

#pagebreak()

#browser-panel("C6", "chr1q", "chr1:248,364,829-248,387,328", "PHR 15 kbp; window 22.5 kbp; terminal gap 3.05 kbp; C arms 1q, 13q, 17q, 19q, 21q, 22q", "1q, 13q, 17q, 19q, 21q, 22q", "_assets/ucsc/panels/chr1q_chr1_248364829_248387328.png", "https://genome.ucsc.edu/cgi-bin/hgTracks?db=hub_3671779_hs1&hgsid=3966979908_lGks6rs34CqmdawD8iwY2YCYKVd3&position=chr1%3A248364829-248387328&pix=1800")

#v(0.07in)

#browser-panel("C6", "chr19q", "chr19:61,677,365-61,707,364", "PHR 20 kbp; window 30 kbp; terminal gap 2.94 kbp; C arms 1q, 13q, 17q, 19q, 21q, 22q", "1q, 13q, 17q, 19q, 21q, 22q", "_assets/ucsc/panels/chr19q_chr19_61677365_61707364.png", "https://genome.ucsc.edu/cgi-bin/hgTracks?db=hub_3671779_hs1&hgsid=3966979908_lGks6rs34CqmdawD8iwY2YCYKVd3&position=chr19%3A61677365-61707364&pix=1800")

#v(0.07in)

#browser-panel("C6", "chr21q", "chr21:45,060,683-45,090,682", "PHR 20 kbp; window 30 kbp; terminal gap 4.35 kbp; C arms 1q, 13q, 17q, 19q, 21q, 22q", "1q, 13q, 17q, 19q, 21q, 22q", "_assets/ucsc/panels/chr21q_chr21_45060683_45090682.png", "https://genome.ucsc.edu/cgi-bin/hgTracks?db=hub_3671779_hs1&hgsid=3966979908_lGks6rs34CqmdawD8iwY2YCYKVd3&position=chr21%3A45060683-45090682&pix=1800")

#pagebreak()

#browser-panel("C6", "chr22q", "chr22:51,287,427-51,324,926", "PHR 25 kbp; window 37.5 kbp; terminal gap 2.73 kbp; C arms 1q, 13q, 17q, 19q, 21q, 22q", "1q, 13q, 17q, 19q, 21q, 22q", "_assets/ucsc/panels/chr22q_chr22_51287427_51324926.png", "https://genome.ucsc.edu/cgi-bin/hgTracks?db=hub_3671779_hs1&hgsid=3966979908_lGks6rs34CqmdawD8iwY2YCYKVd3&position=chr22%3A51287427-51324926&pix=1800")

#v(0.07in)

#browser-panel("C7", "chr21p", "chr21:1-727,502", "PHR 485 kbp; window 728 kbp; terminal gap 2.50 kbp; C arms 13p, 14p, 15p, 21p, 22p", "13p, 14p, 15p, 21p, 22p", "_assets/ucsc/panels/chr21p_chr21_1_727502.png", "https://genome.ucsc.edu/cgi-bin/hgTracks?db=hub_3671779_hs1&hgsid=3966979908_lGks6rs34CqmdawD8iwY2YCYKVd3&position=chr21%3A1-727502&pix=1800")

#pagebreak()

#browser-panel("C7", "chr14p", "chr14:1-555,002", "PHR 370 kbp; window 555 kbp; terminal gap 2.08 kbp; C arms 13p, 14p, 15p, 21p, 22p", "13p, 14p, 15p, 21p, 22p", "_assets/ucsc/panels/chr14p_chr14_1_555002.png", "https://genome.ucsc.edu/cgi-bin/hgTracks?db=hub_3671779_hs1&hgsid=3966979908_lGks6rs34CqmdawD8iwY2YCYKVd3&position=chr14%3A1-555002&pix=1800")

#v(0.07in)

#browser-panel("C7", "chr15p", "chr15:1-607,502", "PHR 405 kbp; window 608 kbp; terminal gap 3.26 kbp; C arms 13p, 14p, 15p, 21p, 22p", "13p, 14p, 15p, 21p, 22p", "_assets/ucsc/panels/chr15p_chr15_1_607502.png", "https://genome.ucsc.edu/cgi-bin/hgTracks?db=hub_3671779_hs1&hgsid=3966979908_lGks6rs34CqmdawD8iwY2YCYKVd3&position=chr15%3A1-607502&pix=1800")

#v(0.07in)

#browser-panel("C7", "chr22p", "chr22:1-750,002", "PHR 500 kbp; window 750 kbp; terminal gap 4.14 kbp; C arms 13p, 14p, 15p, 21p, 22p", "13p, 14p, 15p, 21p, 22p", "_assets/ucsc/panels/chr22p_chr22_1_750002.png", "https://genome.ucsc.edu/cgi-bin/hgTracks?db=hub_3671779_hs1&hgsid=3966979908_lGks6rs34CqmdawD8iwY2YCYKVd3&position=chr22%3A1-750002&pix=1800")

#pagebreak()

#browser-panel("C8", "chr15q", "chr15:99,565,696-99,753,195", "PHR 125 kbp; window 188 kbp; terminal gap 2.84 kbp; C arms 15q", "15q", "_assets/ucsc/panels/chr15q_chr15_99565696_99753195.png", "https://genome.ucsc.edu/cgi-bin/hgTracks?db=hub_3671779_hs1&hgsid=3966979908_lGks6rs34CqmdawD8iwY2YCYKVd3&position=chr15%3A99565696-99753195&pix=1800")

#v(0.07in)

#browser-panel("C9", "chr16p", "chr16:1-37,502", "PHR 25 kbp; window 37.5 kbp; terminal gap 2.17 kbp; C arms 16p", "16p", "_assets/ucsc/panels/chr16p_chr16_1_37502.png", "https://genome.ucsc.edu/cgi-bin/hgTracks?db=hub_3671779_hs1&hgsid=3966979908_lGks6rs34CqmdawD8iwY2YCYKVd3&position=chr16%3A1-37502&pix=1800")

#pagebreak()

#browser-panel("C10", "chr17p", "chr17:1-22,502", "PHR 15 kbp; window 22.5 kbp; terminal gap 1.68 kbp; C arms 17p", "17p", "_assets/ucsc/panels/chr17p_chr17_1_22502.png", "https://genome.ucsc.edu/cgi-bin/hgTracks?db=hub_3671779_hs1&hgsid=3966979908_lGks6rs34CqmdawD8iwY2YCYKVd3&position=chr17%3A1-22502&pix=1800")

#pagebreak()

#browser-panel("C11", "chr1p", "chr1:1-442,502", "PHR 295 kbp; window 443 kbp; terminal gap 2.71 kbp; C arms 1p, 5q, 6q, 8p", "1p, 5q, 6q, 8p", "_assets/ucsc/panels/chr1p_chr1_1_442502.png", "https://genome.ucsc.edu/cgi-bin/hgTracks?db=hub_3671779_hs1&hgsid=3966979908_lGks6rs34CqmdawD8iwY2YCYKVd3&position=chr1%3A1-442502&pix=1800")

#pagebreak()

#browser-panel("C11", "chr8p", "chr8:1-15,002", "PHR 10 kbp; window 15 kbp; terminal gap 1.88 kbp; C arms 1p, 5q, 6q, 8p", "1p, 5q, 6q, 8p", "_assets/ucsc/panels/chr8p_chr8_1_15002.png", "https://genome.ucsc.edu/cgi-bin/hgTracks?db=hub_3671779_hs1&hgsid=3966979908_lGks6rs34CqmdawD8iwY2YCYKVd3&position=chr8%3A1-15002&pix=1800")

#pagebreak()

#browser-panel("C11", "chr5q", "chr5:181,752,940-182,045,439", "PHR 195 kbp; window 292 kbp; terminal gap 1.51 kbp; C arms 1p, 5q, 6q, 8p", "1p, 5q, 6q, 8p", "_assets/ucsc/panels/chr5q_chr5_181752940_182045439.png", "https://genome.ucsc.edu/cgi-bin/hgTracks?db=hub_3671779_hs1&hgsid=3966979908_lGks6rs34CqmdawD8iwY2YCYKVd3&position=chr5%3A181752940-182045439&pix=1800")

#pagebreak()

#browser-panel("C11", "chr6q", "chr6:171,909,129-172,126,628", "PHR 145 kbp; window 218 kbp; terminal gap 2.75 kbp; C arms 1p, 5q, 6q, 8p", "1p, 5q, 6q, 8p", "_assets/ucsc/panels/chr6q_chr6_171909129_172126628.png", "https://genome.ucsc.edu/cgi-bin/hgTracks?db=hub_3671779_hs1&hgsid=3966979908_lGks6rs34CqmdawD8iwY2YCYKVd3&position=chr6%3A171909129-172126628&pix=1800")

#v(0.07in)

#browser-panel("C12", "chr2q", "chr2:242,516,753-242,696,752", "PHR 120 kbp; window 180 kbp; terminal gap 2.63 kbp; C arms 2q, 20p", "2q, 20p", "_assets/ucsc/panels/chr2q_chr2_242516753_242696752.png", "https://genome.ucsc.edu/cgi-bin/hgTracks?db=hub_3671779_hs1&hgsid=3966979908_lGks6rs34CqmdawD8iwY2YCYKVd3&position=chr2%3A242516753-242696752&pix=1800")

#pagebreak()

#browser-panel("C12", "chr20p", "chr20:1-150,002", "PHR 100 kbp; window 150 kbp; terminal gap 2.70 kbp; C arms 2q, 20p", "2q, 20p", "_assets/ucsc/panels/chr20p_chr20_1_150002.png", "https://genome.ucsc.edu/cgi-bin/hgTracks?db=hub_3671779_hs1&hgsid=3966979908_lGks6rs34CqmdawD8iwY2YCYKVd3&position=chr20%3A1-150002&pix=1800")

#v(0.07in)

#browser-panel("C13", "chr4p", "chr4:1-97,502", "PHR 65 kbp; window 97.5 kbp; terminal gap 3.09 kbp; C arms 4p", "4p", "_assets/ucsc/panels/chr4p_chr4_1_97502.png", "https://genome.ucsc.edu/cgi-bin/hgTracks?db=hub_3671779_hs1&hgsid=3966979908_lGks6rs34CqmdawD8iwY2YCYKVd3&position=chr4%3A1-97502&pix=1800")

#pagebreak()

#browser-panel("C14", "chrXq", "chrX:153,764,567-154,259,566", "PHR 330 kbp; window 495 kbp; terminal gap 2.65 kbp; C arms Xq, Yq", "Xq, Yq", "_assets/ucsc/panels/chrXq_chrX_153764567_154259566.png", "https://genome.ucsc.edu/cgi-bin/hgTracks?db=hub_3671779_hs1&hgsid=3966979908_lGks6rs34CqmdawD8iwY2YCYKVd3&position=chrX%3A153764567-154259566&pix=1800")

#v(0.07in)

#browser-panel("C15", "chrXp", "chrX:1-750,002", "PHR 500 kbp; window 750 kbp; terminal gap 1.58 kbp; C arms Xp, Yp", "Xp, Yp", "_assets/ucsc/panels/chrXp_chrX_1_750002.png", "https://genome.ucsc.edu/cgi-bin/hgTracks?db=hub_3671779_hs1&hgsid=3966979908_lGks6rs34CqmdawD8iwY2YCYKVd3&position=chrX%3A1-750002&pix=1800")
