// Standalone CHM13/hs1 UCSC browser slide suite for PHR review.
// Generated by _scripts/render_ucsc_browser_suite.py.

#set page(
  width: 13.33in,
  height: 7.5in,
  margin: (x: 0.18in, y: 0.14in),
)
#set text(font: ("DejaVu Sans", "Liberation Sans"), size: 10pt, lang: "en")
#set par(justify: false, leading: 0.64em)

#let col-title = rgb("#1a3a6b")
#let col-muted = rgb("#555555")
#let col-rule = rgb("#ccd6e0")

#let browser-slide(num, label, region, phr, gap, img) = {
  grid(
    rows: (0.52in, 1fr, 0.16in),
    row-gutter: 0.02in,
    [
      #grid(
        columns: (1fr, 1fr),
        align: (left, right),
        [#text(size: 12pt, weight: "semibold", fill: col-title)[#num #h(0.10in) #label]],
        [#text(size: 9.2pt, fill: col-muted)[#region]],
      )
      #line(length: 100%, stroke: 0.6pt + col-rule)
      #text(size: 7.6pt, fill: col-muted)[#phr #h(0.12in) #gap]
    ],
    box(width: 100%, height: 100%)[
      #image(img, width: 100%, height: 100%, fit: "contain")
    ],
    align(center)[#text(size: 5.8pt, fill: col-muted)[UCSC Genome Browser CHM13/hs1; chm13.phrs.bed custom track visible; terminal end included in window]],
  )
}

#align(center + horizon)[
  #block(width: 11.2in)[
    #align(center)[#text(size: 28pt, weight: "bold", fill: col-title)[CHM13/hs1 PHR UCSC Browser Suite]]
    #v(0.28in)
    #text(size: 14pt)[Rendered 37 main UCSC browser-image slides from `chm13.phrs.bed`. Every panel uses a terminal-anchored 1.5x zoom-out around the PHR interval and keeps the chromosome end in view.]
    #v(0.18in)
    #text(size: 12pt, fill: col-muted)[Audit: `architecture_per_arm.tsv` lists 41 arms, while `chm13.phrs.bed` contains 37 intervals. Missing from the CHM13 BED: chr6_p, chr13_p, chrY_p, chrY_q. Extra in the CHM13 BED relative to the architecture audit: none.]
    #v(0.18in)
    #text(size: 10.5pt, fill: col-muted)[Manifest: `manifest.tsv`; audit: `audit_37_vs_41.tsv`; cached UCSC HTML and cropped panels: `_assets/ucsc/`.]
  ]
]

#pagebreak()
#browser-slide("01", "chr1p", "chr1:1-442502", "PHR BED chr1:2706-297706; inclusive PHR 295,001 bp; browser window 442,502 bp", "p-arm terminal gap 2,706 bp", "_assets/ucsc/panels/chr1p_chr1_1_442502.png")

#pagebreak()
#browser-slide("02", "chr1q", "chr1:248364829-248387328", "PHR BED chr1:248369277-248384276; inclusive PHR 15,000 bp; browser window 22,500 bp", "q-arm terminal gap 3,052 bp", "_assets/ucsc/panels/chr1q_chr1_248364829_248387328.png")

#pagebreak()
#browser-slide("03", "chr10p", "chr10:1-105002", "PHR BED chr10:2489-72489; inclusive PHR 70,001 bp; browser window 105,002 bp", "p-arm terminal gap 2,489 bp", "_assets/ucsc/panels/chr10p_chr10_1_105002.png")

#pagebreak()
#browser-slide("04", "chr10q", "chr10:134488135-134758134", "PHR BED chr10:134574995-134754994; inclusive PHR 180,000 bp; browser window 270,000 bp", "q-arm terminal gap 3,140 bp", "_assets/ucsc/panels/chr10q_chr10_134488135_134758134.png")

#pagebreak()
#browser-slide("05", "chr11p", "chr11:1-352502", "PHR BED chr11:1736-236736; inclusive PHR 235,001 bp; browser window 352,502 bp", "p-arm terminal gap 1,736 bp", "_assets/ucsc/panels/chr11p_chr11_1_352502.png")

#pagebreak()
#browser-slide("06", "chr12p", "chr12:1-105002", "PHR BED chr12:2783-72783; inclusive PHR 70,001 bp; browser window 105,002 bp", "p-arm terminal gap 2,783 bp", "_assets/ucsc/panels/chr12p_chr12_1_105002.png")

#pagebreak()
#browser-slide("07", "chr12q", "chr12:133287049-133324548", "PHR BED chr12:133297274-133322273; inclusive PHR 25,000 bp; browser window 37,500 bp", "q-arm terminal gap 2,275 bp", "_assets/ucsc/panels/chr12q_chr12_133287049_133324548.png")

#pagebreak()
#browser-slide("08", "chr13q", "chr13:113551687-113566686", "PHR BED chr13:113553247-113563246; inclusive PHR 10,000 bp; browser window 15,000 bp", "q-arm terminal gap 3,440 bp", "_assets/ucsc/panels/chr13q_chr13_113551687_113566686.png")

#pagebreak()
#browser-slide("09", "chr14p", "chr14:1-555002", "PHR BED chr14:2075-372075; inclusive PHR 370,001 bp; browser window 555,002 bp", "p-arm terminal gap 2,075 bp", "_assets/ucsc/panels/chr14p_chr14_1_555002.png")

#pagebreak()
#browser-slide("10", "chr15p", "chr15:1-607502", "PHR BED chr15:3258-408258; inclusive PHR 405,001 bp; browser window 607,502 bp", "p-arm terminal gap 3,258 bp", "_assets/ucsc/panels/chr15p_chr15_1_607502.png")

#pagebreak()
#browser-slide("11", "chr15q", "chr15:99565696-99753195", "PHR BED chr15:99625359-99750358; inclusive PHR 125,000 bp; browser window 187,500 bp", "q-arm terminal gap 2,837 bp", "_assets/ucsc/panels/chr15q_chr15_99565696_99753195.png")

#pagebreak()
#browser-slide("12", "chr16p", "chr16:1-37502", "PHR BED chr16:2168-27168; inclusive PHR 25,001 bp; browser window 37,502 bp", "p-arm terminal gap 2,168 bp", "_assets/ucsc/panels/chr16p_chr16_1_37502.png")

#pagebreak()
#browser-slide("13", "chr16q", "chr16:96097875-96330374", "PHR BED chr16:96172817-96327816; inclusive PHR 155,000 bp; browser window 232,500 bp", "q-arm terminal gap 2,558 bp", "_assets/ucsc/panels/chr16q_chr16_96097875_96330374.png")

#pagebreak()
#browser-slide("14", "chr17p", "chr17:1-22502", "PHR BED chr17:1679-16679; inclusive PHR 15,001 bp; browser window 22,502 bp", "p-arm terminal gap 1,679 bp", "_assets/ucsc/panels/chr17p_chr17_1_22502.png")

#pagebreak()
#browser-slide("15", "chr17q", "chr17:84209398-84276897", "PHR BED chr17:84229104-84274103; inclusive PHR 45,000 bp; browser window 67,500 bp", "q-arm terminal gap 2,794 bp", "_assets/ucsc/panels/chr17q_chr17_84209398_84276897.png")

#pagebreak()
#browser-slide("16", "chr18p", "chr18:1-397502", "PHR BED chr18:2017-267017; inclusive PHR 265,001 bp; browser window 397,502 bp", "p-arm terminal gap 2,017 bp", "_assets/ucsc/panels/chr18p_chr18_1_397502.png")

#pagebreak()
#browser-slide("17", "chr19p", "chr19:1-315002", "PHR BED chr19:1962-211962; inclusive PHR 210,001 bp; browser window 315,002 bp", "p-arm terminal gap 1,962 bp", "_assets/ucsc/panels/chr19p_chr19_1_315002.png")

#pagebreak()
#browser-slide("18", "chr19q", "chr19:61677365-61707364", "PHR BED chr19:61684426-61704425; inclusive PHR 20,000 bp; browser window 30,000 bp", "q-arm terminal gap 2,939 bp", "_assets/ucsc/panels/chr19q_chr19_61677365_61707364.png")

#pagebreak()
#browser-slide("19", "chr2q", "chr2:242516753-242696752", "PHR BED chr2:242574127-242694126; inclusive PHR 120,000 bp; browser window 180,000 bp", "q-arm terminal gap 2,626 bp", "_assets/ucsc/panels/chr2q_chr2_242516753_242696752.png")

#pagebreak()
#browser-slide("20", "chr20p", "chr20:1-150002", "PHR BED chr20:2698-102698; inclusive PHR 100,001 bp; browser window 150,002 bp", "p-arm terminal gap 2,698 bp", "_assets/ucsc/panels/chr20p_chr20_1_150002.png")

#pagebreak()
#browser-slide("21", "chr20q", "chr20:66052756-66210255", "PHR BED chr20:66102369-66207368; inclusive PHR 105,000 bp; browser window 157,500 bp", "q-arm terminal gap 2,887 bp", "_assets/ucsc/panels/chr20q_chr20_66052756_66210255.png")

#pagebreak()
#browser-slide("22", "chr21p", "chr21:1-727502", "PHR BED chr21:2505-487505; inclusive PHR 485,001 bp; browser window 727,502 bp", "p-arm terminal gap 2,505 bp", "_assets/ucsc/panels/chr21p_chr21_1_727502.png")

#pagebreak()
#browser-slide("23", "chr21q", "chr21:45060683-45090682", "PHR BED chr21:45066333-45086332; inclusive PHR 20,000 bp; browser window 30,000 bp", "q-arm terminal gap 4,350 bp", "_assets/ucsc/panels/chr21q_chr21_45060683_45090682.png")

#pagebreak()
#browser-slide("24", "chr22p", "chr22:1-750002", "PHR BED chr22:4138-504138; inclusive PHR 500,001 bp; browser window 750,002 bp", "p-arm terminal gap 4,138 bp", "_assets/ucsc/panels/chr22p_chr22_1_750002.png")

#pagebreak()
#browser-slide("25", "chr22q", "chr22:51287427-51324926", "PHR BED chr22:51297197-51322196; inclusive PHR 25,000 bp; browser window 37,500 bp", "q-arm terminal gap 2,730 bp", "_assets/ucsc/panels/chr22q_chr22_51287427_51324926.png")

#pagebreak()
#browser-slide("26", "chr3q", "chr3:200723449-201105948", "PHR BED chr3:200846363-201101362; inclusive PHR 255,000 bp; browser window 382,500 bp", "q-arm terminal gap 4,586 bp", "_assets/ucsc/panels/chr3q_chr3_200723449_201105948.png")

#pagebreak()
#browser-slide("27", "chr4p", "chr4:1-97502", "PHR BED chr4:3087-68087; inclusive PHR 65,001 bp; browser window 97,502 bp", "p-arm terminal gap 3,087 bp", "_assets/ucsc/panels/chr4p_chr4_1_97502.png")

#pagebreak()
#browser-slide("28", "chr4q", "chr4:193304946-193574945", "PHR BED chr4:193392741-193572740; inclusive PHR 180,000 bp; browser window 270,000 bp", "q-arm terminal gap 2,205 bp", "_assets/ucsc/panels/chr4q_chr4_193304946_193574945.png")

#pagebreak()
#browser-slide("29", "chr5q", "chr5:181752940-182045439", "PHR BED chr5:181848925-182043924; inclusive PHR 195,000 bp; browser window 292,500 bp", "q-arm terminal gap 1,515 bp", "_assets/ucsc/panels/chr5q_chr5_181752940_182045439.png")

#pagebreak()
#browser-slide("30", "chr6q", "chr6:171909129-172126628", "PHR BED chr6:171978883-172123882; inclusive PHR 145,000 bp; browser window 217,500 bp", "q-arm terminal gap 2,746 bp", "_assets/ucsc/panels/chr6q_chr6_171909129_172126628.png")

#pagebreak()
#browser-slide("31", "chr7p", "chr7:1-262502", "PHR BED chr7:3375-178375; inclusive PHR 175,001 bp; browser window 262,502 bp", "p-arm terminal gap 3,375 bp", "_assets/ucsc/panels/chr7p_chr7_1_262502.png")

#pagebreak()
#browser-slide("32", "chr7q", "chr7:160559929-160567428", "PHR BED chr7:160560602-160565601; inclusive PHR 5,000 bp; browser window 7,500 bp", "q-arm terminal gap 1,827 bp", "_assets/ucsc/panels/chr7q_chr7_160559929_160567428.png")

#pagebreak()
#browser-slide("33", "chr8p", "chr8:1-15002", "PHR BED chr8:1881-11881; inclusive PHR 10,001 bp; browser window 15,002 bp", "p-arm terminal gap 1,881 bp", "_assets/ucsc/panels/chr8p_chr8_1_15002.png")

#pagebreak()
#browser-slide("34", "chr9p", "chr9:1-60002", "PHR BED chr9:3488-43488; inclusive PHR 40,001 bp; browser window 60,002 bp", "p-arm terminal gap 3,488 bp", "_assets/ucsc/panels/chr9p_chr9_1_60002.png")

#pagebreak()
#browser-slide("35", "chr9q", "chr9:150279748-150617247", "PHR BED chr9:150390025-150615024; inclusive PHR 225,000 bp; browser window 337,500 bp", "q-arm terminal gap 2,223 bp", "_assets/ucsc/panels/chr9q_chr9_150279748_150617247.png")

#pagebreak()
#browser-slide("36", "chrXp", "chrX:1-750002", "PHR BED chrX:1579-501579; inclusive PHR 500,001 bp; browser window 750,002 bp", "p-arm terminal gap 1,579 bp", "_assets/ucsc/panels/chrXp_chrX_1_750002.png")

#pagebreak()
#browser-slide("37", "chrXq", "chrX:153764567-154259566", "PHR BED chrX:153926918-154256917; inclusive PHR 330,000 bp; browser window 495,000 bp", "q-arm terminal gap 2,649 bp", "_assets/ucsc/panels/chrXq_chrX_153764567_154259566.png")
